############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Elements"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "Others"

[[main]]
parent = "Others"
name = "Labs 介绍"
url = "/labs"
weight = 1

[[main]]
parent = "Others"
name = "黑客松介绍"
url = "/contact"
weight = 2

[[main]]
parent = "Others"
name = "活动"
url = "/contact"
weight = 3

[[main]]
parent = "Others"
name = "归零食堂 介绍"
url = "/authors"
weight = 4

[[main]]
parent = "Others"
name = "QI 介绍"
url = "/categories"
weight = 5

[[main]]
parent = "Others"
name = "技术社区 介绍"
url = "/Labs"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
