# defaultContentLanguageInSubdir must be true for this to work.

# Other languages redirects
# [[redirects]]
# from = '/zh/**'
# to = '/zh/404.html'
# status = 404

# Default language must be last.
# [[redirects]]
# from = '/**'
# to = '/en/404.html'
# status = 404
